name = "TDAOpt"
uuid = "818b9442-f5db-4c58-bcff-64ce83b3c071"
authors = ["SidV <sidv@Lazuli.local> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
